#!/bin/sh
# Lodenica backend container entrypoint — first-boot bootstrap then exec CMD.
#
# The /app/.env file lives INSIDE the container (not bind-mounted from the
# host) so we can freely rewrite it on every boot to match the compose-
# provided environment. This is necessary because PHP's built-in server
# (`php artisan serve`) re-bootstraps Laravel per request and dotenv
# can return inconsistent values when both an .env file AND OS env vars
# define the same key — the safe path is to make .env the single source.

set -e

# 1. Vendor — install on first boot, or whenever the named volume is empty.
if [ ! -f /app/vendor/autoload.php ]; then
    echo "==> composer install (first boot)…"
    composer install --no-interaction --prefer-dist
fi

# 2. Write a fresh .env from compose-provided env vars. APP_KEY is
#    preserved between restarts via the named bootstrap_cache volume:
#    we stash it there once generated.
KEY_CACHE=/app/bootstrap/cache/.docker-app-key
if [ -f "$KEY_CACHE" ]; then
    APP_KEY=$(cat "$KEY_CACHE")
else
    APP_KEY="base64:$(php -r 'echo base64_encode(random_bytes(32));')"
    echo "$APP_KEY" > "$KEY_CACHE"
fi

echo "==> Writing /app/.env from compose environment…"
cat > /app/.env <<EOF
# Generated by docker compose on container start. Edits will be lost on
# the next \`docker compose up\`. To override values, edit docker-compose.yml
# (service "backend", environment block).
APP_NAME=Lodenica
APP_ENV=${APP_ENV:-local}
APP_KEY=${APP_KEY}
APP_DEBUG=${APP_DEBUG:-true}
APP_TIMEZONE=UTC
APP_URL=${APP_URL:-http://localhost:8000}
APP_LOCALE=sk
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=sk_SK

LOG_CHANNEL=${LOG_CHANNEL:-stack}
LOG_STACK=${LOG_STACK:-single}
LOG_LEVEL=${LOG_LEVEL:-debug}

DB_CONNECTION=${DB_CONNECTION:-pgsql}
DB_HOST=${DB_HOST:-postgres}
DB_PORT=${DB_PORT:-5432}
DB_DATABASE=${DB_DATABASE:-lodenica_php}
DB_USERNAME=${DB_USERNAME:-lodenica}
DB_PASSWORD=${DB_PASSWORD:-lodenica}

CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:5173}

SESSION_DRIVER=${SESSION_DRIVER:-array}
QUEUE_CONNECTION=${QUEUE_CONNECTION:-sync}
CACHE_STORE=${CACHE_STORE:-array}
BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
EOF
chmod 644 /app/.env

# 3. Migrations + seeder. The seeder is idempotent: it only inserts demo
#    data on an empty DB and creates the default admin if it's missing.
echo "==> Running migrations + seeder…"
php artisan migrate --force
php artisan db:seed --force

echo "==> Booting: $*"
exec "$@"
